PAY_TYPE_NICK={}; //PayTypeNick
PAY_TYPE_NICK.WEIXIN='微信支付';
PAY_TYPE_NICK.PEERPAY='三方代付';
PAY_TYPE_NICK.ALIPAY='支付宝付款';
PAY_TYPE_NICK.BANKCARDPAY='银行卡支付';
PAY_TYPE_NICK.CODPAY='货到付款';
PAY_TYPE_NICK.BAIDUPAY='百度钱包';
PAY_TYPE_NICK.PRESENTTAKE='赠品领用';
PAY_TYPE_NICK.COUPONPAY='优惠抵扣';
PAY_TYPE_NICK.BULKPURCHASE='分销采购';

PAY_STATUS_NICK={};
PAY_STATUS_NICK.TRADE_NO_CREATE_PAY='未提交';
PAY_STATUS_NICK.WAIT_BUYER_PAY='待付款';
PAY_STATUS_NICK.WAIT_SELLER_SEND_GOODS='待发货';
PAY_STATUS_NICK.TRADE_BUYER_SIGNED='已完成';
PAY_STATUS_NICK.TRADE_CLOSED='已退款';
PAY_STATUS_NICK.TRADE_CLOSED_BY_USER='被取消';
PAY_STATUS_NICK.ALL_CLOSED='已关闭';
PAY_STATUS_NICK.WAIT_BUYER_CONFIRM_GOODS='待收货';

SHIP_TYPE_NICK={};
SHIP_TYPE_NICK.fetch='自提';
SHIP_TYPE_NICK.express='配送';
